#!/usr/bin/env bash

remaining=`acpi -b | tail -1 | cut -d, -f2 | tr -d '[:space:]%'`
status=`acpi -b | tail -1 | awk -F"[, ]" '{printf $3}'`

if [ $status = "Discharging" ]; then
    icon="󰂁"
else
    icon=""
fi

echo $icon $remaining%
