#!/usr/bin/env bash

# Default
width=$(tput cols 2>/dev/null || echo 80)
height=1

while getopts ":h:" opt; do
    case ${opt} in
        h )
            height=${OPTARG}
            ;;
        \? )
            echo "Usage: $(basename "$0") [-h <height>]" >&2
            exit 1
            ;;
    esac
done

shift $((OPTIND -1))

awk -v term_cols="${width}" -v term_lines="${height}" '
    BEGIN {
        s="/\\";
        total_cols=term_cols*term_lines;
        for (colnum = 0; colnum<total_cols; colnum++) {
            r = 255-(colnum*255/total_cols);
            g = (colnum*510/total_cols);
            b = (colnum*255/total_cols);
            if (g>255) g = 510-g;
            printf "\033[48;2;%d;%d;%dm", r,g,b;
            printf "\033[38;2;%d;%d;%dm", 255-r,255-g,255-b;
            printf "%s\033[0m", substr(s,colnum%2+1,1);
            if (colnum%term_cols==term_cols-1) printf "\n";
        }
        printf "\n";
    }
'
