#!/usr/bin/env bash

contexts=$(docker context ls | awk '{if ($1 != "NAME") print $1}')

selected_option=$(printf "%s\n" "${contexts[@]}" | fzf --prompt="Select docker contexts: " --height=~50% --layout=reverse --border --exit-0)

docker context use $selected_option
