#!/usr/bin/env bash

#-------------------------------------------------
# ------------ kconf ------------------
# author: github.com/razzkumar
#-------------------------------------------------

# Disclaimer
# must put all k8s configs inside ~/.kube/conf/ before running this script 

unset KUBECONFIG

KUBECONFIG=$(find ~/.kube/conf/ -type f | tr '\n' ':') kubectl config view --flatten > ~/.kube/config 

chmod 600 ~/.kube/config

export KUBECONFIG=~/.kube/config

kubectx
