#!/usr/bin/env bash

print_usage(){
    echo "Usage: kubesecret -s <secret-name>"
    echo "Options:"
    echo "  -s : Name of the secret"
    echo "  -n : Namespace of the secret (default: default)"
    echo "  -o : Output file (default: secret-data.txt)"
    echo "  -h : Help"
}


while getopts "s:n:h" opt; do
  case $opt in
    s) secret_name="$OPTARG"
    ;;
    n) namespace="$OPTARG"
    ;;
    o) output_file="$OPTARG"
    ;;
    h) print_usage
       exit 0
    ;;
    \?) echo "Invalid option -$OPTARG" >&2
    ;;
  esac
done


if [ -z "$secret_name" ]; then
    echo "Secret name is required"
    print_usage
    exit 1
fi

if [ -z "$namespace" ]; then
    namespace="default"
fi

if [ -z "$output_file" ]; then
    output_file="secret-data"
fi

kubectl get secret $secret_name -n $namespace -o json | jq -r '.data | with_entries(select(.value != null)) | to_entries[] | .key + ": " + (.value | @base64d)' > $output_file.txt

echo "Secret data written to $output_file.txt"
