#!/usr/bin/env bash

# Exit silently if xidlehook is not installed
if ! command -v xidlehook &> /dev/null; then
  exit 0
fi

export PRIMARY_DISPLAY="$(xrandr | awk '/ primary/{print $1}')"

# paru -S xidlehook
xidlehook \
  `# Don't lock when there's a fullscreen application` \
  --not-when-fullscreen \
  `# Don't lock when there's audio playing` \
  --not-when-audio \
  `# Dim the screen after 120 seconds, undim if user becomes active` \
  --timer 120 \
    'xrandr --output "$PRIMARY_DISPLAY" --brightness .3' \
    'xrandr --output "$PRIMARY_DISPLAY" --brightness 1' \
  `# Undim & lock after 30 more seconds` \
  --timer 30 \
    'xrandr --output "$PRIMARY_DISPLAY" --brightness 1; lock' \
    '' \
