return {
    "lukas-reineke/indent-blankline.nvim",
    event = "BufReadPre",
    opts = {
        char = "┊",
        use_treesitter = true,
        space_char_blankline = " ",
        show_current_context = false,
        show_current_context_start = false,
        buftype_exclude = {
            "nofile",
            "terminal",
        },
        filetype_exclude = {
            "man",
            "help",
            "dart",
            "lazy",
            "alpha",
            "aerial",
            "lspinfo",
            "vimwiki",
            "Trouble",
            "NvimTree",
            "startify",
            "dashboard",
            "checkhealth",
            "diagnosticpopup",
            "TelescopePrompt",
            "TelescopeResults",
        },
        context_patterns = {
            "class",
            "return",
            "function",
            "method",
            "^if",
            "^while",
            "jsx_element",
            "^for",
            "^object",
            "^table",
            "block",
            "arguments",
            "if_statement",
            "else_clause",
            "jsx_element",
            "jsx_self_closing_element",
            "try_statement",
            "catch_clause",
            "import_statement",
            "operation_type",
        },
    },
}
